#spring.application.name=loan-service
# 
#server.port=1994
# 
#spring.datasource.url=jdbc:mysql://localhost:3306/microserviceDB
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.show-sql=true
##spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#
##eureka.client.registerWithEureka= true
#eureka.client.registerWithEureka= true
##eureka.client.fetchRegistry= true
#eureka.client.fetchRegistry= false
#
#eureka.client.serviceUrl.defaultZone= http://localhost:1008/eureka/
##eureka.client.instance.hostname= localhost
##eureka.client.instance.instanceaId= ${spring.application.name}:${randaom.value}

#spring:
  #data:
    #mongodb:
      #host: localhost
      #port: 27017
      #database: ProfileDB
      #repositories:
        #enabled: true  
        
server:
  port: 1994        
        
        
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/microservicedb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: loan-service     
  cloud:
    stream:
      bindings:
        loan-out:
          content-type: application/json
          destination: loan-topic
          group: orchestrator 

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}